### ISSUE TITLE
Upstream application icons and branding should be respected

### ISSUE THREAD

**Issue by chergert** [pop-os/iso#103]
* Distribution - [Pop!_OS Intel ISO](https://d1vhcvzji58n1j.cloudfront.net/pop-os/iso/beta/27/pop-os_amd64_27.iso), 17.10
 * pop-icon-theme

**Issue/Bug Description**

The `pop-icon-theme` is overriding the branding of [Builder](https://wiki.gnome.org/Apps/Builder). Our application icon is our branding and having it overridden by default is not helpful to us.

**Steps to reproduce (if you know)**

Install Builder from apt or via Flatpak.

**Expected behaviour**

Application developers icons and branding are respected.

**Other Notes**

I understand Pop!_OS might have a desire for a unified style on the OS that is shipped. But consider third-party application authors and how their brand is equally important to them.

Imagine shipping an app in the Android store and it having different branding on Sony phones.

You might consider breaking up the icon theme into tiers with a core set of icons for applications shipped as part of the OS and an additional package users can install to "override all my applications to look like my OS instead of as the authors intended".

**Comment by jackpot51** [comment]
Thanks for reporting this. We will discuss your suggestion of moving application icons to a separate package, thus using the default icon for most applications.

**Comment by isantop** [comment]
This issue was moved to pop-os/icon-theme#21
