### ISSUE TITLE
Audio Disabled on Install

### ISSUE THREAD

**Issue by Appalbarry** [pop-os/iso#105]
barryrueger@pop-os:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Artful Aardvark (development branch)
Release:	17.10
Codename:	artful

**Issue/Bug Description**

After a fresh install to my Dell Latitude E6400 laptop audio is disabled until the Pop/Gnome audio level is lowered from maximum.  There after audio works as expected.

**Steps to reproduce (if you know)**

(I have gone through this twice)

1. Fresh install of Pop_OS accepting all default settings except for choosing to "Erase Disc and install Pop_OS"

2. After install, configure WIFI and password.

3. Open Firefox (or Chrome) and visit Youtube. Click to play video.

4. There is no sound.  the audio control in the browser is at the default level.

5. Opening the audio level slider from the top right hand speaker icon (see before.png) shows that audio level is set to maximum.
![image](https://user-images.githubusercontent.com/1308152/31039609-d6adb270-a533-11e7-9a27-36d5cb466736.png)

6. Lowering the audio level to something less than maximum makes sound work. (see after.png)
![image](https://user-images.githubusercontent.com/1308152/31039626-e9eb9bae-a533-11e7-8fc6-79f697cda219.png)

7. Thereafter audio work as expected, even if the slider is set back to maximum volume.

**Expected behaviour**

Audio works properly after a fresh install.

**Comment by WatchMkr** [comment]
Does audio work as expected after a reboot?

**Comment by Appalbarry** [comment]
1) I rebooted form USB and the audio was disabled in the Live Boot instance.

2) I did another fresh install.
3) Opened Firefox and tried Youtube. Audio did not work.
4)BEFORE CHANGING ANY SETTINGS rebooted the computer.
5) Audio still did not work.
6) Changed audio level as before, audio works.
7) Rebooted again, audio still works.

If it helps:

barryrueger@pop-os:~$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: Intel [HDA Intel], device 0: 92HD71B7X Analog [92HD71B7X Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
barryrueger@pop-os:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Intel [HDA Intel], device 0: 92HD71B7X Analog [92HD71B7X Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by Appalbarry** [comment]
Problem remains with 17.10.

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#42
