### ISSUE TITLE
Display Settings Doesn't Show Apply Button on Load

### ISSUE THREAD

**Issue by skulkingfox** [pop-os/iso#109]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Issue/Bug Description**

When in the Display Settings with multiple monitors using the Join Displays tab changing the position of the monitors and/or changing the primary monitor does not cause the Apply button to appear. You have to swap to another displays option tab (like mirror) for the apply button to appear, then swap back, redo the changes you want and then hit apply. 

At this point, the changes save/apply and all is well. 

![screenshot from 2017-09-30 17-55-20](https://user-images.githubusercontent.com/8932534/31050726-90e29578-a608-11e7-9864-8a448bb713b5.png)

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#41
