### ISSUE TITLE
Cannot boot on MSI GE63VR-7RE Raider without `nomodeset`

### ISSUE THREAD

**Issue by Shamash2014** [pop-os/iso#111]
**Reporter info**

```
msi GE63VR 7RE

GTX1060 + i7-7700HQ+120hz screen
```

**Issue/Bug Description**

Cannot boot without nomodeset. With nomodeset can install, but on boot of installed system blank screen. 

**Steps to reproduce (if you know)**

**Expected behaviour**

Possible to boot and have at list non 1024X768 resolution and run system without recovery mode

**Other Notes**

**Comment by jackpot51** [comment]
Did you try the NVIDIA ISO?

**Comment by Shamash2014** [comment]
Everything the same

**Comment by Shamash2014** [comment]
Laprop screen turns off

**Comment by WatchMkr** [comment]
Does your laptop have nvidia optimus?

Please try to use the Intel/AMD iso and remove "splash" from the kernel line.

**Comment by Shamash2014** [comment]
yeah, it has optimus, I even can boot to tty console and mangle with `prime-select`. Prime-select nvidia shows loop with black X server trying to boot. 

Prime-select intel results in just the whole screen turned off / blank. 

Setting `i915.nomodeset=0` helps to boot, but without hardware acceleration. 

Platform: KabyLake (i7-7700HQ) & GTX 1060

**Comment by RicardoEPRodrigues** [comment]
I have a similar issue.

If I install the Nvidia ISO it runs smoothly, yet only on the dedicated card. If I try to `prime-select intel` it shows the loading screen and as soon has it disables the dedicated card it freezes.

For the Intel builds I have the same issue with extra steps, where I have to start with `nouveau.modeset=0` install nvidia proprietary drivers and reboot. Then first problem arises.

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#40
