### ISSUE TITLE
Installer fails

### ISSUE THREAD

**Issue by bZez** [pop-os/iso#113]
<details>
<summary><b>Reporter info</b></summary>
<pre><code>
pop_os                      
    description: Ordinateur Bloc-notes
    produit: ENLE11BZ (ENLE11BZ_073D_2.11)
    fabriquant: Packard Bell
    version: V2.11
    numéro de série: NXC1UMF0153120297A7200
    bits: 64 bits
    fonctionnalités: smbios-2.7 dmi-2.7 smp vsyscall32
    configuration: chassis=notebook family=ASPIRE sku=ENLE11BZ_073D_2.11 uuid=53B36052-8A31-E2AE-4719-7C05071D0846
  *-core
       description: Carte mère
       produit: EG70_BZ
       fabriquant: Packard Bell
       identifiant matériel: 0
       version: Base Board Version
       numéro de série: NBC1U1100231101B9A7200
       emplacement: Base Board Chassis Location
     *-firmware
          description: BIOS
          fabriquant: Insyde Corp.
          identifiant matériel: 0
          version: V2.11
          date: 12/13/2012
          taille: 128KiB
          capacité: 4032KiB
          fonctionnalités: pci upgrade shadowing cdboot bootselect socketedrom edd int13floppynec int13floppytoshiba int13floppy360 int13floppy1200 int13floppy720 int13floppy2880 int9keyboard int10video acpi usb uefi
     *-cpu
          description: CPU
          produit: AMD E1-1200 APU with Radeon(tm) HD Graphics
          fabriquant: Advanced Micro Devices [AMD]
          identifiant matériel: 4
          information bus: cpu@0
          version: AMD E1-1200 APU with Radeon(tm) HD Graphics
          numéro de série: NotSupport
          emplacement: Socket FT1
          taille: 1397MHz
          capacité: 1400MHz
          bits: 64 bits
          horloge: 100MHz
          fonctionnalités: x86-64 fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni monitor ssse3 cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch ibs skinit wdt hw_pstate vmmcall arat npt lbrv svm_lock nrip_save pausefilter cpufreq
          configuration: cores=2 enabledcores=2 threads=2
        *-cache:0
             description: L1 cache
             identifiant matériel: 8
             emplacement: L1 Cache
             taille: 128KiB
             capacité: 128KiB
             horloge: 1GHz (1.0ns)
             fonctionnalités: pipeline-burst internal write-back unified
             configuration: level=1
        *-cache:1
             description: L2 cache
             identifiant matériel: 9
             emplacement: L2 Cache
             taille: 1MiB
             capacité: 1MiB
             horloge: 1GHz (1.0ns)
             fonctionnalités: pipeline-burst internal write-back unified
             configuration: level=2
     *-memory
          description: Mémoire Système
          identifiant matériel: 13
          emplacement: Carte mère
          taille: 6GiB
        *-bank:0
             description: SODIMM DDR3 Synchrone Unbuffered (Unregistered) 800 MHz (1,2 ns)
             produit: ACR512X64D3S16C11G
             fabriquant: Kingston
             identifiant matériel: 0
             numéro de série: 602E51BB
             emplacement: DIMM 0
             taille: 4GiB
             bits: 64 bits
             horloge: 800MHz (1.2ns)
        *-bank:1
             description: SODIMM DDR3 Synchrone Unbuffered (Unregistered) 667 MHz (1,5 ns)
             produit: NT2GC64B88G0NS-CG
             fabriquant: Nanya Technology
             identifiant matériel: 1
             numéro de série: 2D751012
             emplacement: DIMM 1
             taille: 2GiB
             bits: 64 bits
             horloge: 667MHz (1.5ns)
     *-pci:0
          description: Host bridge
          produit: Family 14h Processor Root Complex
          fabriquant: Advanced Micro Devices, Inc. [AMD]
          identifiant matériel: 100
          information bus: pci@0000:00:00.0
          version: 00
          bits: 32 bits
          horloge: 66MHz
          configuration: latency=32
        *-display
             description: VGA compatible controller
             produit: Wrestler [Radeon HD 7310]
             fabriquant: Advanced Micro Devices, Inc. [AMD/ATI]
             identifiant matériel: 1
             information bus: pci@0000:00:01.0
             version: 00
             bits: 32 bits
             horloge: 33MHz
             fonctionnalités: pm pciexpress msi vga_controller bus_master cap_list rom
             configuration: driver=radeon latency=0
             ressources: irq:32 mémoire:e0000000-efffffff portE/S:3000(taille=256) mémoire:f0300000-f033ffff mémoire:c0000-dffff
        *-multimedia:0
             description: Audio device
             produit: Wrestler HDMI Audio
             fabriquant: Advanced Micro Devices, Inc. [AMD/ATI]
             identifiant matériel: 1.1
             information bus: pci@0000:00:01.1
             version: 00
             bits: 32 bits
             horloge: 33MHz
             fonctionnalités: pm pciexpress msi bus_master cap_list
             configuration: driver=snd_hda_intel latency=0
             ressources: irq:34 mémoire:f0344000-f0347fff
        *-usb:0
             description: USB controller
             produit: FCH USB XHCI Controller
             fabriquant: Advanced Micro Devices, Inc. [AMD]
             identifiant matériel: 10
             information bus: pci@0000:00:10.0
             version: 03
             bits: 64 bits
             horloge: 33MHz
             fonctionnalités: pm msi msix pciexpress xhci bus_master cap_list
             configuration: driver=xhci_hcd latency=0
             ressources: irq:18 mémoire:f0348000-f0349fff
           *-usbhost:0
                produit: xHCI Host Controller
                fabriquant: Linux 4.13.0-12-generic xhci-hcd
                identifiant matériel: 0
                information bus: usb@6
                nom logique: usb6
                version: 4.13
                fonctionnalités: usb-2.00
                configuration: driver=hub slots=2 speed=480Mbit/s
           *-usbhost:1
                produit: xHCI Host Controller
                fabriquant: Linux 4.13.0-12-generic xhci-hcd
                identifiant matériel: 1
                information bus: usb@7
                nom logique: usb7
                version: 4.13
                fonctionnalités: usb-3.00
                configuration: driver=hub slots=2 speed=5000Mbit/s
        *-storage
             description: SATA controller
             produit: FCH SATA Controller [AHCI mode]
             fabriquant: Advanced Micro Devices, Inc. [AMD]
             identifiant matériel: 11
             information bus: pci@0000:00:11.0
             version: 40
             bits: 32 bits
             horloge: 66MHz
             fonctionnalités: storage msi ahci_1.0 bus_master cap_list
             configuration: driver=ahci latency=32
             ressources: irq:31 portE/S:3118(taille=8) portE/S:3124(taille=4) portE/S:3110(taille=8) portE/S:3120(taille=4) portE/S:3100(taille=16) mémoire:f034f000-f034f7ff
        *-usb:1
             description: USB controller
             produit: FCH USB OHCI Controller
             fabriquant: Advanced Micro Devices, Inc. [AMD]
             identifiant matériel: 12
             information bus: pci@0000:00:12.0
             version: 11
             bits: 32 bits
             horloge: 66MHz
             fonctionnalités: ohci bus_master
             configuration: driver=ohci-pci latency=32
             ressources: irq:18 mémoire:f034e000-f034efff
           *-usbhost
                produit: OHCI PCI host controller
                fabriquant: Linux 4.13.0-12-generic ohci_hcd
                identifiant matériel: 1
                information bus: usb@3
                nom logique: usb3
                version: 4.13
                fonctionnalités: usb-1.10
                configuration: driver=hub slots=5 speed=12Mbit/s
        *-usb:2
             description: USB controller
             produit: FCH USB EHCI Controller
             fabriquant: Advanced Micro Devices, Inc. [AMD]
             identifiant matériel: 12.2
             information bus: pci@0000:00:12.2
             version: 11
             bits: 32 bits
             horloge: 66MHz
             fonctionnalités: pm debug ehci bus_master cap_list
             configuration: driver=ehci-pci latency=32
             ressources: irq:17 mémoire:f034d000-f034d0ff
           *-usbhost
                produit: EHCI Host Controller
                fabriquant: Linux 4.13.0-12-generic ehci_hcd
                identifiant matériel: 1
                information bus: usb@1
                nom logique: usb1
                version: 4.13
                fonctionnalités: usb-2.00
                configuration: driver=hub slots=5 speed=480Mbit/s
              *-usb
                   description: Périphérique de stockage de masse
                   produit: Mass Storage Device
                   fabriquant: Generic
                   identifiant matériel: 1
                   information bus: usb@1:1
                   nom logique: scsi2
                   version: 5.00
                   numéro de série: 812320100708
                   fonctionnalités: usb-2.00 scsi emulated scsi-host
                   configuration: driver=usb-storage maxpower=248mA speed=480Mbit/s
                 *-disk
                      description: SCSI Disk
                      produit: Storage Device
                      fabriquant: USB Mass
                      identifiant matériel: 0.0.0
                      information bus: scsi@2:0.0.0
                      nom logique: /dev/sdb
                      taille: 3790MiB (3974MB)
                      fonctionnalités: removable
                      configuration: logicalsectorsize=512 sectorsize=512
                    *-medium
                         identifiant matériel: 0
                         nom logique: /dev/sdb
                         taille: 3790MiB (3974MB)
                         fonctionnalités: partitioned partitioned:dos
                         configuration: signature=570c4aee
                       *-volume
                            description: Windows FAT volume
                            fabriquant: SYSLINUX
                            identifiant matériel: 1
                            nom logique: /dev/sdb1
                            nom logique: /cdrom
                            version: FAT32
                            numéro de série: d4cd-e8ef
                            taille: 3787MiB
                            capacité: 3789MiB
                            fonctionnalités: primary bootable fat initialized
                            configuration: FATs=2 filesystem=fat label=MYLINUXLIVE mount.fstype=vfat mount.options=ro,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro state=mounted
        *-usb:3
             description: USB controller
             produit: FCH USB OHCI Controller
             fabriquant: Advanced Micro Devices, Inc. [AMD]
             identifiant matériel: 13
             information bus: pci@0000:00:13.0
             version: 11
             bits: 32 bits
             horloge: 66MHz
             fonctionnalités: ohci bus_master
             configuration: driver=ohci-pci latency=32
             ressources: irq:18 mémoire:f034c000-f034cfff
           *-usbhost
                produit: OHCI PCI host controller
                fabriquant: Linux 4.13.0-12-generic ohci_hcd
                identifiant matériel: 1
                information bus: usb@4
                nom logique: usb4
                version: 4.13
                fonctionnalités: usb-1.10
                configuration: driver=hub slots=5 speed=12Mbit/s
        *-usb:4
             description: USB controller
             produit: FCH USB EHCI Controller
             fabriquant: Advanced Micro Devices, Inc. [AMD]
             identifiant matériel: 13.2
             information bus: pci@0000:00:13.2
             version: 11
             bits: 32 bits
             horloge: 66MHz
             fonctionnalités: pm debug ehci bus_master cap_list
             configuration: driver=ehci-pci latency=32
             ressources: irq:17 mémoire:f034b000-f034b0ff
           *-usbhost
                produit: EHCI Host Controller
                fabriquant: Linux 4.13.0-12-generic ehci_hcd
                identifiant matériel: 1
                information bus: usb@2
                nom logique: usb2
                version: 4.13
                fonctionnalités: usb-2.00
                configuration: driver=hub slots=5 speed=480Mbit/s
              *-usb
                   description: Vidéo
                   produit: HD WebCam
                   fabriquant: NC.21411.00X30805599LM0009
                   identifiant matériel: 4
                   information bus: usb@2:4
                   version: 0.09
                   fonctionnalités: usb-2.00
                   configuration: driver=uvcvideo maxpower=500mA speed=480Mbit/s
        *-serial NON-RÉCLAMÉ
             description: SMBus
             produit: FCH SMBus Controller
             fabriquant: Advanced Micro Devices, Inc. [AMD]
             identifiant matériel: 14
             information bus: pci@0000:00:14.0
             version: 14
             bits: 32 bits
             horloge: 66MHz
             configuration: latency=0
        *-multimedia:1
             description: Audio device
             produit: FCH Azalia Controller
             fabriquant: Advanced Micro Devices, Inc. [AMD]
             identifiant matériel: 14.2
             information bus: pci@0000:00:14.2
             version: 01
             bits: 64 bits
             horloge: 33MHz
             fonctionnalités: pm msi bus_master cap_list
             configuration: driver=snd_hda_intel latency=32
             ressources: irq:35 mémoire:f0340000-f0343fff
        *-isa
             description: ISA bridge
             produit: FCH LPC Bridge
             fabriquant: Advanced Micro Devices, Inc. [AMD]
             identifiant matériel: 14.3
             information bus: pci@0000:00:14.3
             version: 11
             bits: 32 bits
             horloge: 66MHz
             fonctionnalités: isa bus_master
             configuration: latency=0
        *-pci:0
             description: PCI bridge
             produit: FCH PCI Bridge
             fabriquant: Advanced Micro Devices, Inc. [AMD]
             identifiant matériel: 14.4
             information bus: pci@0000:00:14.4
             version: 40
             bits: 32 bits
             horloge: 66MHz
             fonctionnalités: pci subtractive_decode bus_master
        *-usb:5
             description: USB controller
             produit: FCH USB OHCI Controller
             fabriquant: Advanced Micro Devices, Inc. [AMD]
             identifiant matériel: 14.5
             information bus: pci@0000:00:14.5
             version: 11
             bits: 32 bits
             horloge: 66MHz
             fonctionnalités: ohci bus_master
             configuration: driver=ohci-pci latency=32
             ressources: irq:18 mémoire:f034a000-f034afff
           *-usbhost
                produit: OHCI PCI host controller
                fabriquant: Linux 4.13.0-12-generic ohci_hcd
                identifiant matériel: 1
                information bus: usb@5
                nom logique: usb5
                version: 4.13
                fonctionnalités: usb-1.10
                configuration: driver=hub slots=2 speed=12Mbit/s
        *-pci:1
             description: PCI bridge
             produit: Hudson PCI to PCI bridge (PCIE port 0)
             fabriquant: Advanced Micro Devices, Inc. [AMD]
             identifiant matériel: 15
             information bus: pci@0000:00:15.0
             version: 00
             bits: 32 bits
             horloge: 33MHz
             fonctionnalités: pci pm pciexpress msi ht normal_decode bus_master cap_list
             configuration: driver=pcieport
             ressources: irq:24
        *-pci:2
             description: PCI bridge
             produit: Hudson PCI to PCI bridge (PCIE port 1)
             fabriquant: Advanced Micro Devices, Inc. [AMD]
             identifiant matériel: 15.1
             information bus: pci@0000:00:15.1
             version: 00
             bits: 32 bits
             horloge: 33MHz
             fonctionnalités: pci pm pciexpress msi ht normal_decode bus_master cap_list
             configuration: driver=pcieport
             ressources: irq:25 mémoire:f0200000-f02fffff
           *-network
                description: Interface réseau sans fil
                produit: AR9485 Wireless Network Adapter
                fabriquant: Qualcomm Atheros
                identifiant matériel: 0
                information bus: pci@0000:03:00.0
                nom logique: wlp3s0
                version: 01
                numéro de série: a8:54:b2:96:99:c8
                bits: 64 bits
                horloge: 33MHz
                fonctionnalités: pm msi pciexpress bus_master cap_list rom ethernet physical wireless
                configuration: broadcast=yes driver=ath9k driverversion=4.13.0-12-generic firmware=N/A ip=192.168.0.15 latency=0 link=yes multicast=yes wireless=IEEE 802.11
                ressources: irq:17 mémoire:f0200000-f027ffff mémoire:f0280000-f028ffff
        *-pci:3
             description: PCI bridge
             produit: Hudson PCI to PCI bridge (PCIE port 2)
             fabriquant: Advanced Micro Devices, Inc. [AMD]
             identifiant matériel: 15.2
             information bus: pci@0000:00:15.2
             version: 00
             bits: 32 bits
             horloge: 33MHz
             fonctionnalités: pci pm pciexpress msi ht normal_decode bus_master cap_list
             configuration: driver=pcieport
             ressources: irq:26 portE/S:2000(taille=4096) mémoire:f0100000-f01fffff
           *-network
                description: Ethernet interface
                produit: AR8151 v2.0 Gigabit Ethernet
                fabriquant: Qualcomm Atheros
                identifiant matériel: 0
                information bus: pci@0000:04:00.0
                nom logique: enp4s0
                version: c0
                numéro de série: 7c:05:07:1d:08:46
                capacité: 1Gbit/s
                bits: 64 bits
                horloge: 33MHz
                fonctionnalités: pm msi pciexpress vpd bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
                configuration: autonegotiation=on broadcast=yes driver=atl1c driverversion=1.0.1.1-NAPI latency=0 link=no multicast=yes port=twisted pair
                ressources: irq:33 mémoire:f0100000-f013ffff portE/S:2000(taille=128)
        *-pci:4
             description: PCI bridge
             produit: Hudson PCI to PCI bridge (PCIE port 3)
             fabriquant: Advanced Micro Devices, Inc. [AMD]
             identifiant matériel: 15.3
             information bus: pci@0000:00:15.3
             version: 00
             bits: 32 bits
             horloge: 33MHz
             fonctionnalités: pci pm pciexpress msi ht normal_decode bus_master cap_list
             configuration: driver=pcieport
             ressources: irq:27 portE/S:1000(taille=4096) mémoire:f0000000-f00fffff portE/S:f0400000(taille=2097152)
     *-pci:1
          description: Host bridge
          produit: Family 12h/14h Processor Function 0
          fabriquant: Advanced Micro Devices, Inc. [AMD]
          identifiant matériel: 101
          information bus: pci@0000:00:18.0
          version: 43
          bits: 32 bits
          horloge: 33MHz
     *-pci:2
          description: Host bridge
          produit: Family 12h/14h Processor Function 1
          fabriquant: Advanced Micro Devices, Inc. [AMD]
          identifiant matériel: 102
          information bus: pci@0000:00:18.1
          version: 00
          bits: 32 bits
          horloge: 33MHz
     *-pci:3
          description: Host bridge
          produit: Family 12h/14h Processor Function 2
          fabriquant: Advanced Micro Devices, Inc. [AMD]
          identifiant matériel: 103
          information bus: pci@0000:00:18.2
          version: 00
          bits: 32 bits
          horloge: 33MHz
     *-pci:4
          description: Host bridge
          produit: Family 12h/14h Processor Function 3
          fabriquant: Advanced Micro Devices, Inc. [AMD]
          identifiant matériel: 104
          information bus: pci@0000:00:18.3
          version: 00
          bits: 32 bits
          horloge: 33MHz
          configuration: driver=k10temp
          ressources: irq:0
     *-pci:5
          description: Host bridge
          produit: Family 12h/14h Processor Function 4
          fabriquant: Advanced Micro Devices, Inc. [AMD]
          identifiant matériel: 105
          information bus: pci@0000:00:18.4
          version: 00
          bits: 32 bits
          horloge: 33MHz
     *-pci:6
          description: Host bridge
          produit: Family 12h/14h Processor Function 6
          fabriquant: Advanced Micro Devices, Inc. [AMD]
          identifiant matériel: 106
          information bus: pci@0000:00:18.5
          version: 00
          bits: 32 bits
          horloge: 33MHz
     *-pci:7
          description: Host bridge
          produit: Family 12h/14h Processor Function 5
          fabriquant: Advanced Micro Devices, Inc. [AMD]
          identifiant matériel: 107
          information bus: pci@0000:00:18.6
          version: 00
          bits: 32 bits
          horloge: 33MHz
     *-pci:8
          description: Host bridge
          produit: Family 12h/14h Processor Function 7
          fabriquant: Advanced Micro Devices, Inc. [AMD]
          identifiant matériel: 108
          information bus: pci@0000:00:18.7
          version: 00
          bits: 32 bits
          horloge: 33MHz
     *-scsi:0
          identifiant matériel: 1
          nom logique: scsi0
          fonctionnalités: emulated
        *-disk
             description: ATA Disk
             produit: WDC WD7500BPVT-6
             fabriquant: Western Digital
             identifiant matériel: 0.0.0
             information bus: scsi@0:0.0.0
             nom logique: /dev/sda
             version: 1A01
             numéro de série: WD-WXH1A31R7709
             taille: 698GiB (750GB)
             fonctionnalités: partitioned partitioned:dos
             configuration: ansiversion=5 logicalsectorsize=512 sectorsize=4096 signature=826e540c
           *-volume:0
                description: Windows NTFS volume
                identifiant matériel: 1
                information bus: scsi@0:0.0.0,1
                nom logique: /dev/sda1
                version: 3.1
                numéro de série: ba9f-3f70
                taille: 94MiB
                capacité: 101MiB
                fonctionnalités: primary bootable ntfs initialized
                configuration: clustersize=4096 created=2017-09-03 21:16:00 filesystem=ntfs label=System Reserved state=clean
           *-volume:1
                description: Windows NTFS volume
                identifiant matériel: 2
                information bus: scsi@0:0.0.0,2
                nom logique: /dev/sda2
                version: 3.1
                numéro de série: 922f-eb8d
                taille: 248GiB
                capacité: 248GiB
                fonctionnalités: primary ntfs initialized
                configuration: clustersize=4096 created=2017-10-02 14:38:58 filesystem=ntfs label=STORAGE state=clean
           *-volume:2
                description: Windows NTFS volume
                identifiant matériel: 3
                information bus: scsi@0:0.0.0,3
                nom logique: /dev/sda3
                version: 3.1
                numéro de série: 724b1c12-d15f-af41-80eb-e4108ca9fee5
                taille: 399GiB
                capacité: 399GiB
                fonctionnalités: primary ntfs initialized
                configuration: clustersize=4096 created=2017-10-02 21:30:04 filesystem=ntfs label=BZ state=clean
     *-scsi:1
          identifiant matériel: 2
          nom logique: scsi1
          fonctionnalités: emulated
        *-cdrom
             description: DVD-RAM writer
             produit: DVD-RAM UJ8E1
             fabriquant: MATSHITA
             identifiant matériel: 0.0.0
             information bus: scsi@1:0.0.0
             nom logique: /dev/cdrom
             nom logique: /dev/cdrw
             nom logique: /dev/dvd
             nom logique: /dev/dvdrw
             nom logique: /dev/sr0
             version: 1.00
             fonctionnalités: removable audio cd-r cd-rw dvd dvd-r dvd-ram
             configuration: ansiversion=5 status=nodisc
</code></pre>

 * popOS 17.10 'artful'
 * Live Session Installer (Install Pop_OS 17.10)
</details>

**Issue/Bug Description**

In live session, when I click on Install Pop_OS 17.10 (CD codeIcon on desktop), a window appear and directly disappear, I just see the languages selection list for 1 second.

In Teminal `sudo sh -c 'ubiquity gtk_ui'` return "Bus error"

**Steps to reproduce (if you know)**

**Expected behaviour**

**Other Notes**

**Comment by cassidyjames** [comment]
I believe `Bus error` refers to a hardware issue with the USB drive. @bZez could you try with another physical drive?

**Comment by jackpot51** [comment]
How did you flash the ISO file?

How much memory does your system have?
