### ISSUE TITLE
Pop!_OS won't start because vboxadd-service.service failed to start.

### ISSUE THREAD

**Issue by Justin00015** [pop-os/iso#118]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```lsb_release -a```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```

**Issue/Bug Description**
When starting Pop on a VM, I see that it says "FAILED" for "Starting vboxadd-service.service." The VM then will just not do anything for an unlimited amount of time and forces me to force-shut-down the VM.

**Steps to reproduce (if you know)**
I turn on my VM and I get this message.

**Expected behaviour**
The VM should be able to start the service and boot properly.

**Other Notes**
The VM has EFI disabled. Here is a picture of what happens on the screen: [Picture](https://imgur.com/a/LlKr9)

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#39
