### ISSUE TITLE
Multimonitor mixed DPI work

### ISSUE THREAD

**Issue by sarahpandabeara** [pop-os/iso#121]

**Comment by cassidyjames** [comment]
I've noticed the System76 HiDPI driver thing works well here, except for losing the monitor layout.

**Comment by jackpot51** [comment]
Losing the layout does not mean it works well

**Comment by cassidyjames** [comment]
Hence
> except for

**Comment by sarahpandabeara** [comment]
Is this issue related to the one that Sam and I are having with multiple monitors in workspaces? At least one display (not the main) has flickering from time to time when not in use.

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#38
