### ISSUE TITLE
Pop currently shuts down on critical power. Should suspend.

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/iso#125]
Pop!_OS 17.10

**Issue/Bug Description**
Pop currently shuts down on critical power. Should suspend. This appears to be copying tablet behavior instead of laptop behavior and expectations. I don't see an option in Power for suspend on critical.

**Steps to reproduce (if you know)**
Drain a laptop battery

**Expected behaviour**
Suspend

**Other Notes**

**Comment by WatchMkr** [comment]
The dconf setting is set to suspend but doesn't appear to be adhered to. critical-battery-action

**Comment by kylerchin** [comment]
+1

**Comment by kylerchin** [comment]
It's slightly frustrating on my Galago Pro...

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#35
