### ISSUE TITLE
Add open source apps to the pop repo:

### ISSUE THREAD

**Issue by sarahpandabeara** [pop-os/iso#127]
Atom: popular, fitting our customers, and should be installable from the included repos
Mattermost: the tool used for our community communications
Telegram: There's an active system76 community

**Comment by kylerchin** [comment]
+1 for Atom and Brave Browser...

**Comment by jackpot51** [comment]
Due to the amount of time required to do this, I am moving it to Post-Release

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#34
