### ISSUE TITLE
System76 Driver installed when System76 hardware is detected

### ISSUE THREAD

**Issue by sarahpandabeara** [pop-os/iso#132]

**Comment by isantop** [comment]
Was it determined that the Driver should be instalable from the repo? If so, that's a pretty trivial update.

**Comment by sarahpandabeara** [comment]
Is it the driver that should be put in the Pop!_OS repo? Or is it the system76 repo that should be added to Pop!_OS?

**Comment by sarahpandabeara** [comment]
@isantop @jackpot51 ^ Either of you have an answer regarding the above question?

**Comment by jackpot51** [comment]
I would prefer the latter, adding the System76 repo to Pop!_OS during install

**Comment by jackpot51** [comment]
I believe this is the most logical way to manage things. A script will run during install. This script will add the system76-dev/stable PPA and install the driver when the correct hardware is detected.

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#32
