### ISSUE TITLE
Pop! Shop Updater stalls at "Waiting for package manager lock."

### ISSUE THREAD

**Issue by Appalbarry** [pop-os/iso#136]
* Distribution - (run ```cat /etc/os-release```)

barryrueger@pop-os:~$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/system76/pop-distro/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

**Issue/Bug Description**
Trying to update software from Pop!Shop app does not work.

**Steps to reproduce (if you know)**
1) Open Pop!Shop app
2) Choose "Updates" tab
3) App displays two available updates:
- Operating System Updates - 38 components with updates:
- Startup Applications 3.26.1
4) Click either an "Update" button or the "Update All" button
5) Update initiates, but stalls at "Waiting for package manager lock."
6) App returns to state it was in before clicking "Update"

This is on a fresh USB install of a freshly downloaded ISO yesterday.

**Expected behaviour**
Updates install themselves.

**Other Notes**

**Comment by Appalbarry** [comment]
Followup. 
Ran apt-get update.
apt-get upgrade failed with: **E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.** 
Ran dpkg; restarted Pop!Shop app; updates worked fine.
Terminal output below.

`barryrueger@pop-os:~$ sudo apt-get update
[sudo] password for barryrueger: 
Hit:1 http://us.archive.ubuntu.com/ubuntu artful InRelease
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease                   
Hit:3 http://dl.google.com/linux/chrome/deb stable Release                     
Hit:4 http://us.archive.ubuntu.com/ubuntu artful-updates InRelease             
Hit:5 http://us.archive.ubuntu.com/ubuntu artful-backports InRelease           
Hit:6 http://security.ubuntu.com/ubuntu artful-security InRelease              
Hit:7 http://ppa.launchpad.net/system76/pop/ubuntu artful InRelease      
Reading package lists... Done                      
barryrueger@pop-os:~$ sudo apt-get upgrade
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 
barryrueger@pop-os:~$ ^C
barryrueger@pop-os:~$ sudo dpkg --configure -a
Setting up console-setup (1.166ubuntu7) ...
update-initramfs: deferring update (trigger activated)
Setting up tracker-miner-fs (2.0.2-1) ...
Installing new version of config file /etc/xdg/autostart/tracker-miner-apps.desktop ...
Installing new version of config file /etc/xdg/autostart/tracker-miner-fs.desktop ...
Setting up tk8.6 (8.6.7-1ubuntu1) ...
Setting up libpam-systemd:amd64 (234-2ubuntu12) ...
Setting up pop-default-settings (1.2.27) ...
Leaving 'diversion of /etc/os-release to /etc/os-release.diverted by pop-default-settings'
Setting up cups-filters (1.17.9-0ubuntu1) ...
Setting up cups-browsed (1.17.9-0ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3) ...
Setting up curl (7.55.1-1ubuntu2) ...
Processing triggers for cups (2.2.4-7ubuntu2) ...
Setting up gnome-shell (3.26.1-0ubuntu1pop0) ...
Processing triggers for initramfs-tools (0.125ubuntu11) ...
update-initramfs: Generating /boot/initrd.img-4.13.0-12-generic
Setting up gnome-control-center (1:3.26.1-0ubuntu2) ...
Setting up pop-session (1.2.27) ...
Setting up pop-desktop (1.1.27) ...
Processing triggers for libc-bin (2.26-0ubuntu1) ...
barryrueger@pop-os:~$ 
`

**Comment by isantop** [comment]
This issue was moved to pop-os/shop#26

**Comment by hsek** [comment]
thanks a lot 
it worked for me

**Comment by hsek** [comment]
being a Linux beginner i am very happy to see such strong community thanks

**Comment by jonbmartin** [comment]
worked! thank you!
