### ISSUE TITLE
Custom Partitioning allows for overwrite of liveusb

### ISSUE THREAD

**Issue by brs17** [pop-os/iso#142]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 31 (noNVIDIA)

**Issue/Bug Description**
During installation when choosing to custom partition the drives, the liveusb drive is listed and can be reformatted. This should not be allowed.

**Steps to reproduce (if you know)**
Choose to custom partition the drives in Ubiquity. Notice that /dev/sdb(most likely) is the liveusb drive.

**Expected behaviour**
Mounted drives running the live-cd should not be listed as a possible install medium.

**Other Notes**

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#23
