### ISSUE TITLE
Typing in location and hitting 'enter', autocomplete does not select

### ISSUE THREAD

**Issue by brs17** [pop-os/iso#145]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 31 (noNVIDIA)

**Issue/Bug Description**
During installation, when typing in a location, hitting 'enter' with an auto-complete suggested will not update the time zone. See picture below.

Typing "Denver":
![img_20171011_151449](https://user-images.githubusercontent.com/7460774/31467465-4d91777a-ae97-11e7-890b-090ad1b8fd66.jpg)

After hitting "Enter":
![img_20171011_151457](https://user-images.githubusercontent.com/7460774/31467476-56bd0de6-ae97-11e7-967c-be8ee01caf04.jpg)

**Steps to reproduce (if you know)**
See above

**Expected behaviour**
Should autocomplete and update location

**Other Notes**
Currently you have to arrow down and select on the dropdown autocomplete to successfully get the city you would like.

**Comment by isantop** [comment]
This issue was moved to pop-os/gnome-initial-setup#13
