### ISSUE TITLE
Without internet connection, "Connect your online accounts" page should not appear

### ISSUE THREAD

**Issue by brs17** [pop-os/iso#146]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 31 (noNVIDIA)

**Issue/Bug Description**
When going through the installer without an Internet connection, the "Connect your Online account" page should not appear. When selecting on the various social media accounts, an error page occurs, and for the services that do not return an error...they should.

Therefore this entire page is not useful without an Internet connection and should be skipped if such is the case.

**Comment by isantop** [comment]
This issue was moved to pop-os/gnome-initial-setup#12
