### ISSUE TITLE
Able to create invalid usernames

### ISSUE THREAD

**Issue by brs17** [pop-os/iso#147]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 31 (noNVIDIA)

**Issue/Bug Description**
The installer allows for the username of '..' to be created. No errors appear. Obviously though, the installation hangs as a home directory cannot be named '..'.

**Expected behaviour**
Error message should appear for such a username selection.

**Comment by isantop** [comment]
This issue was moved to pop-os/gnome-initial-setup#11
