### ISSUE TITLE
Pressing the mute key on the keyboard will toggle mute repeatedly

### ISSUE THREAD

**Issue by brs17** [pop-os/iso#148]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**
 
```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 31 (noNVIDIA)
Experienced bug on Oryx Pro 2 and Galago 3

**Issue/Bug Description**
Hitting the mute button on the keyboard will occasionally result in mute toggling very quickly on/off.
If a terminal window is open when the toggling begins, the terminal will become unresponsive. Switching to another ttyl and going back will unfreeze the terminal. 

**Steps to reproduce (if you know)**
Unable to reproduce consistently. Press the mute button until the issue arises.

**Expected behaviour**
Mute button toggles once.

**Other Notes**
Want to test Pop!_OS on a machine with a different EC.

**Comment by brs17** [comment]
Was able to reproduce bug on Gazp7.

**Comment by jackpot51** [comment]
I was unable to reproduce on a Dell XPS 13

**Comment by WatchMkr** [comment]
I think this is firmware. It occurs in Ubuntu as well and has for as long as I can remember. Let's check with support to see if they get tickets on it.

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#22
