### ISSUE TITLE
GNOME Initial Setup > Privacy > Location Services choice is not adhered to when enabled

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/iso#15]
**Reporter info**

```
 * Distribution - (run ```lsb_release -a```)
Pop!_OS 17.04 Alpha
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
gnome-initial-setup
```

**Actual issue**

Privacy > Location Services choice is not adhered to when enabled.

**Steps to reproduce (if you knew)**

Set Location Services to Enabled during GNOME Initial Setup. Login and observe the location setting in the System Menu.

**Expected behaviour**

Location Services setting is retained in the user account.

**Other Note (feature-request, question, etc...)**

**Comment by sarahpandabeara** [comment]
@WatchMkr is this related or different to the bug we encountered with location services not accurately capturing a location or allowing you to select "next"?

**Comment by WatchMkr** [comment]
this is different

**Comment by WatchMkr** [comment]
@sarahpandabeara This needs to be re-tested with Pop!_OS 17.10. I think this bug is fixed already.

**Comment by isantop** [comment]
This issue was moved to pop-os/gnome-initial-setup#15
