### ISSUE TITLE
GRUB hidden timeout cannot be interrupted with shift

### ISSUE THREAD

**Issue by jackpot51** [pop-os/iso#151]
This issue affects real hardware. The code in Ubuntu's grub checks during hidden sleep for ESC or either shift key. The test for ESC works, but then dumps you into the indecipherable GRUB command prompt. The test for shift does not work on real hardware.

**Comment by jackpot51** [comment]
It is not possible to patch GRUB in our own repository, due to it requiring a signature by Ubuntu.

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#18
