### ISSUE TITLE
Bug with Document Viewer printing wrong multiples

### ISSUE THREAD

**Issue by sarahpandabeara** [pop-os/iso#155]
Carl and I found that this is specific to Pop!_OS where printing a PDF from Document Viewer in any multiple other than 1 sends the request off more than once (ie: ask for 2 copies, get 4).

Confirmed: Not an issue with Libre open docs.
Confirmed: Not an issue with Ubuntu Document Viewer

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#17
