### ISSUE TITLE
Show list of packages to be updated in the software updater

### ISSUE THREAD

**Issue by dhollinger** [pop-os/iso#157]
Have been recently testing out Solus for family use and noticed that the software updater lists all packages to be updated before you actually update. This would be nice to see in the Pop!_OS updater so that I can see which packages are set to be updated before I confirm the update.

**Comment by brs17** [comment]
@dhollinger How does the Pop!_Shop functionality look now? You can currently see available updates in the Pop!_Shop "Updates" tab.

**Comment by dhollinger** [comment]
I see that! It's awesome, thanks!
