### ISSUE TITLE
Ubiquity > Drop down arrow contrast and Remove (or only show) Skip when necessary

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/iso#16]
**Reporter info**

```
 * Distribution - (run ```lsb_release -a```)
Pop OS 17.04
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
ubiquity
```

**Actual issue**

During installation the drop down arrow for more detail is invisible (it appears left of the text describing the installation step).

The skip button doesn't appear to do anything. If true remove or at least show only when valid.

**Steps to reproduce (if you knew)**

Install Pop OS

**Expected behaviour**

Arrow is visible. Skip button does something or doesn't show.

**Other Note (feature-request, question, etc...)**

**Comment by JosephMcc** [comment]
Wouldn't it be better to open the two bugs as separate issues? They don't really seem related to one another. The invisible arrow is very possibly a theming issue.

**Comment by isantop** [comment]
This issue was moved to pop-os/gtk-theme#78
