### ISSUE TITLE
Installer does not allow for dual boot with Windows

### ISSUE THREAD

**Issue by brs17** [pop-os/iso#160]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 35 (noNVIDIA)

**Issue/Bug Description**
On Oryxp3, Ubiquity installer recognizes "Windows Boot Manager" but only recommends erasing the disk to install Pop!_OS by itself.

**Steps to reproduce (if you know)**
Attempt to install Pop!_OS with Windows 10 already installed.

**Expected behaviour**
The Ubiquity installer should provide an option to dual boot the two machines. 

**Other Notes**
Screenshot:

![screenshot from 2017-10-13 14-10-09](https://user-images.githubusercontent.com/7460774/31566817-874357ca-b029-11e7-9ab0-578d15392153.png)

Gparted can see and resize the windows partition and fast boot has been disabled.

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#14

**Comment by forrestblade** [comment]
The only real solution to this right now is to shrink the Windows 10 partition prior to attempting to a dual boot install.

**Comment by brs17** [comment]
@forrestblade thanks for the suggestion. We are actually in the works to release a new installer with Pop!_OS 18.04. We will be releasing a test iso in the coming days. In the meantime feel free to take a peak at the repositories for this new project: front-end: https://github.com/pop-os/installer back-end: https://github.com/pop-os/distinst

**Comment by winuxue** [comment]
Any update about this?

**Comment by WatchMkr** [comment]
Yes, the new installer in Pop!_OS supports dual boot. Instructions are here:

https://support.system76.com/articles/dual-booting/

One caveat, for Windows we've found that you need a separate 512 MB /boot/efi partition because Windows creates one with only enough space for their bootloader.

**Comment by jeremiascb** [comment]
Sabe me dizer como resolvo esse problema? Se eu criar essa partição de 512 MB, como fica o boot?

**Comment by GottfriedCP** [comment]
Is it okay to have two ESPs on one hard drive?
