### ISSUE TITLE
Pop!_OS Splash screen is squished with AMD graphics card

### ISSUE THREAD

**Issue by brs17** [pop-os/iso#164]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 35 (noNVIDIA)

**Issue/Bug Description**
Installed Pop!_OS on a Leopard WS with an AMD Radeon RX 580. The splash screen displays squished with no animation.

**Expected behaviour**
Normal splash screen animation.

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#12
