### ISSUE TITLE
Improper default program for decompressing formats

### ISSUE THREAD

**Issue by brs17** [pop-os/iso#167]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
Pop!_OS (20171016) build

**Issue/Bug Description**
Compression formats .7z and .tar.xz, and .iso default to open in "Files" not the "Archive Manager" and thus results in the compressed file being decompressed by default. 

**Steps to reproduce (if you know)**
In "Files" select on a *.7z, *.tar.xz, or *.iso file. 

**Expected behaviour**
The compressed file should open up in the "Archive Manager" displaying the contents of the compressed file.

**Other Notes**
.7z, .iso, .tar.xz should have the same default program as .zip or .tar.gz

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#11
