### ISSUE TITLE
Firefox and Thunderbird can't be installed with Pop!_Shop

### ISSUE THREAD

**Issue by Xeboc** [pop-os/iso#168]
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
Package: pop-shop
Version: 0.2.6-8
```

**Issue/Bug Description**

Thunderbird and Firefox are common programs and aren't currently found in Pop!_Shop

**Steps to reproduce (if you know)**

Search for these programs.

**Expected behaviour**

Be able to install these common internet programs.

**Comment by brs17** [comment]
There is no AppStream data on either of these packages and therefore will not show up in the Pop!_Shop.  We are aware of this and hope to have a fix in a later version of Pop!_OS.

**Comment by brs17** [comment]
@cassidyjames @btkostner Let's take a peak at what we can do to include the AppStream data for Firefox...and I guess anything else that we ship in Pop!_OS by default (for now).

**Comment by btkostner** [comment]
elementary ships a package from this repo for things like steam. We will need to add some firefox metadata.

http://bazaar.launchpad.net/~elementary-os/elementaryos/appstream-data-pantheon-dep11/files

**Comment by isantop** [comment]
This issue was moved to pop-os/shop#24
