### ISSUE TITLE
Gnome-disk-utility does not show model of NVME drive

### ISSUE THREAD

**Issue by brs17** [pop-os/iso#170]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.
```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
gnome-disk-utility 3.26

**Issue/Bug Description**
Model for NVME drives are not displayed in the gnome-disk-utility. `cat /sys/class/block/nvme0n1/device/model` shows the model number that should be displayed.

**Comment by jackpot51** [comment]
Reported on launchpad: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1724370

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#10
