### ISSUE TITLE
Pop!_Shop should provide Run option when searching for a program already installed

### ISSUE THREAD

**Issue by brs17** [pop-os/iso#173]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.
```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
Pop!_OS 17.10

**Issue/Bug Description**
Under the "Home" tab, when searching for a program that is already installed on the system, there should be an "Open" button to open the program. 

Currently:
![screenshot from 2017-10-18 10-30-28](https://user-images.githubusercontent.com/7460774/31731617-dd915524-b3f2-11e7-9fa8-bb6835ea98ab.png)

Desired:
![screenshot from 2017-10-18 10-56-20](https://user-images.githubusercontent.com/7460774/31731682-0c19a536-b3f3-11e7-8718-1d948b88d64a.png)

**Comment by isantop** [comment]
This issue was moved to pop-os/shop#23
