### ISSUE TITLE
"Printer is added" notification spams users.

### ISSUE THREAD

**Issue by isantop** [pop-os/iso#178]
**Reporter info**

```
 * Distribution - Pop_OS 17.10
 * Related Application and/or Package Version - cups 2.2.4-7ubuntu2
```

**Issue/Bug Description**
With some printers and some network environments, the "Printer is added" notifications can show every few minutes. Even when this isn't the case, it may be annoying for the notification to pop up every time the users logs in, or reconnects to the network.

**Steps to reproduce (if you know)**
Connect to a network that has an available dnssd network printer connected, eg. an HP.

**Expected behaviour**
System silently adds the printer, or no action is taken. 

**Other Notes**
Can be disabled with `sudo nano /etc/cups/cups-browsed.conf` and changing `BrowseRemoteProtocols dnssd cups` to `BrowseRemoteProtocols none` as per 
https://www.reddit.com/r/pop_os/comments/77mh4x/printer_added_notifications_every_few_minutes/
and https://ubuntuforums.org/showthread.php?t=2330752

**Comment by cassidyjames** [comment]
Yeah I agree the notifications are excessive and unnecessary; we shouldn't be informing users of the magic happening behind the scenes, printers should just be automatically and silently available when they're on the network.

**Comment by isantop** [comment]
Another problem; I have added a printer manually (so that scanning works) and when I connect to the network, I have two identical printers added. We shouldn't auto-add printers that are manually added to the system (or, ones that have been manually removed after being automatically added).

**Comment by Jeymz** [comment]
Auto adding printers from the network should be option in my opinion. Or at the very least if I delete an auto added printer, it should not re-add itself.

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#8
