### ISSUE TITLE
No headphone sound.

### ISSUE THREAD

**Issue by ryanpcmcquen** [pop-os/iso#180]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/system76/pop-distro/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
```

**Issue/Bug Description**

No headphone sound. Sound works out of internal speakers.

**Steps to reproduce (if you know)**

Install Pop!_OS.

**Expected behaviour**

There would be sound out of the headphones.

**Other Notes**

Let me know what other diagnostic data would be helpful. I would _love_ to get this working. Pop!_OS is amazing!

**Comment by jackpot51** [comment]
What machine are you running Pop!_OS on?

**Comment by ryanpcmcquen** [comment]
A Sager NP7338.

**Comment by jackpot51** [comment]
Is there a line out jack you can try?

**Comment by ryanpcmcquen** [comment]
No, the only audio ports are headphone and microphone (both 3.5mm).

**Comment by vincenttaglia** [comment]
I'm having the same issue on my Kudu Pro, except the built in speakers and the built in microphone both do not work as well. I also installed the System76 drivers and restarted but that didn't help.

**Comment by ryanpcmcquen** [comment]
I've tried everything here:

http://support.system76.com/articles/audio/

```
$ lspci -v | grep -A6 Audio
00:03.0 Audio device: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller (rev 06)
	Subsystem: CLEVO/KAPOK Computer Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller
	Flags: bus master, fast devsel, latency 0, IRQ 30
	Memory at f7a14000 (64-bit, non-prefetchable) [size=16K]
	Capabilities: <access denied>
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel

--
00:1b.0 Audio device: Intel Corporation 8 Series/C220 Series Chipset High Definition Audio Controller (rev 05)
	Subsystem: CLEVO/KAPOK Computer 8 Series/C220 Series Chipset High Definition Audio Controller
	Flags: bus master, fast devsel, latency 0, IRQ 33
	Memory at f7a10000 (64-bit, non-prefetchable) [size=16K]
	Capabilities: <access denied>
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel
```
```
$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: HDMI [HDA Intel HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 9: HDMI 3 [HDMI 3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 10: HDMI 4 [HDMI 4]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 0: VT1802 Analog [VT1802 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 2: VT1802 Alt Analog [VT1802 Alt Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
I also have the `system76-driver` installed (sound did not work before it). I think my system is similar to some older System76 laptops even though it is not a System76 machine.

**Comment by vincenttaglia** [comment]
I just installed pulse audio, deleted the config files from pulse, and that ended up fixing the problem somehow. I did have pulse audio config files there from a restored backup, so that may or may not have something to do with it.

Also, ryanpcmcquen, I don't think you are supposed to install system76 drivers unless you have a system76 machine, but I may be wrong.

**Comment by ryanpcmcquen** [comment]
@vincenttaglia I'm pretty sure my machine is close to one of the older System76 machines.

**Comment by isantop** [comment]
@ryanpcmcquen Unless it's actually a System76-Branded computer, the Driver will not work on it, and it's designed not to. All System76 computers have certain BIOS modifications to implement things in more linux-friendly ways. The driver expects this, but that may cause issues even with systems similar to System76 machines.

**Comment by ryanpcmcquen** [comment]
@isantop, noted. It still had no headphone sound without the driver though.

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#7
