### ISSUE TITLE
Unplugging ethernet while in standby fails

### ISSUE THREAD

**Issue by brs17** [pop-os/iso#186]
```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
Pop!_OS 17.10

**Issue/Bug Description**
On OryxPro3 and 2, when Ethernet is disconnected when the computer is in a standby state, the machine fails to disconnect from Ethernet and regain WI-fi connection upon system resume.

On Kudu4, the Ethernet connection properly disconnects upon resume but takes >1minute to reconnect to a wired connection if Ethernet cable is plugged in again.

**Steps to reproduce (if you know)**
Connect machine to both wired ethernet connection as well as to a Wifi connection. Put the machine in standby. Unplug ethernet connection. Resume system. 

**Expected behaviour**
Ethernet connection should disconnect and Wifi should reconnect after system resumes. 

**Other Notes**
Ethernet connected icon is still visible in the system menu upon resume. Internet connection unavailable.

![screenshot from 2017-10-23 13-32-02](https://user-images.githubusercontent.com/7460774/31913491-7802fd28-b804-11e7-9c21-dbca04bb2e94.png)

**Comment by isantop** [comment]
Oryx issue also happens on oryp1

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#5
