### ISSUE TITLE
Initial Setup doesn't check if usernames are valid

### ISSUE THREAD

**Issue by Hronom** [pop-os/iso#191]
Hello, on the initial setup screen, when you enter username that used for user home directory threre is no check is all charas are lowercased. This allow you to enter name `Hronom` that not allowed by the system, the correct is `hronom`. This bug don't allow user to continue use Pop OS because initial setup closes without errors and don't initialize reboot  of the system with compeltition of setup.

**Comment by isantop** [comment]
This issue was moved to pop-os/gnome-initial-setup#10
