### ISSUE TITLE
"Open in Terminal" is shown twice in Nautilus when using WebDAV or Samba

### ISSUE THREAD

**Issue by bakaschwarz** [pop-os/iso#195]
**Reporter info**
![screen-34](https://user-images.githubusercontent.com/11743101/33631728-5a780110-da03-11e7-8462-6b214876bfeb.png)
**Issue/Bug Description**

Nautilus displays the "Open in Terminal" option twice when using WebDAV to connect
to a Nextcloud server. Both options function the same as far as i could tell.

![screen-35](https://user-images.githubusercontent.com/11743101/33631840-9ceaeb52-da03-11e7-94f9-9c9720fa91d5.png)

**Steps to reproduce (if you know)**

Setup a fresh installation of Pop and add Nextcloud as an Account while the initial user setup takes place.
After that just open Nautilus and click on your Nextcloud connection in the left menu.

**Expected behaviour**

Only one option with "Open in Terminal" like in the local filesystem.

**Other Notes**

This seems to happen in Samba shares as well.

**Comment by isantop** [comment]
Confirmed here.

**Comment by humaidq** [comment]
Also happens on Fedora, so this is not Ubuntu/PopOS specific bug.

**Comment by jacobgkau** [comment]
It looks like this was resolved upstream. In 20.04 LTS:

- A Nextcloud server (via WebDAV) only displays one `Open in Terminal` option.
- A Samba share only displays one `Open in Terminal` option.
- An sftp directory displays an `Open in Remote Terminal` option and an `Open in Local Terminal` option.
