### ISSUE TITLE
Pop!_Shop: Failed to Fetch Updates

### ISSUE THREAD

**Issue by MarkoPetteri** [pop-os/iso#197]
**Reporter info**

Newbie user with a newbie problem. If this is the wrong place to post problems like this, please redirect me. I already posted to reddit about this too.

Pop!_OS 17.10 64-bit | GNOME 3.26.2 | AMD Ryzen 5 1400 Quad-Core Processor × 8 | 7,8 GB RAM | 25 GB SSD + 120 GB SSD | GeForce GT 630/PCIe/SSE2 | Focusrite Scarlett 2i2

 * Related Application

Pop!_Shop

**Issue/Bug Description**

When I open Pop!_Shop! this message starts popping up and stacking up. If I use another workspace it pops up there. I can't use Pop!_Shop if I don't close them all. I can't close Pop!_Shop through the tab next to Activities. Also I cannot find one of the pop up messages and so cannot close them all.

I could get around this by rebooting or killing it through the terminal but I think this is not a behaviour we're looking for. Hence the post.

Here's the contents of the message:
" io.elementary.appcenter

Failed to Fetch Updates

E: The repository 'http://ppa.launchpad.net/gregory-hainaut/pcsx2.official.ppa/ubuntu artful Release' does not have a Release file. W: Updating from such a repository can't be done securely, and is therefore disabled by default. W: See apt-secure(8) manpage for repository creation and user configuration details "

**Steps to reproduce**

Launch Pop!_Shop.

**Comment by isantop** [comment]
This issue was moved to pop-os/shop#37
