### ISSUE TITLE
Top bar panels remain light, while the default chosen theme is "Pop-dark-slim".

### ISSUE THREAD

**Issue by akshymalvia** [pop-os/iso#198]
**Reporter info**

![image](https://user-images.githubusercontent.com/30196863/34951606-dc85d8b8-fa3c-11e7-8af0-17bbe2309978.png)

 * Related Application and/or Package Version - apt policy $PACKAGE NAME

pop-gnome-shell or pop-gtk-theme or pop-desktop

**Issue/Bug Description**

When opening the notifications panel or notification icons panel they're light, and the application menu panel is also remain light, in fact every panel associated with "top bar" is light while all other UI components are dark in a proper manner as they're expected to be with "Pop-dark-slim" theme.

![image](https://user-images.githubusercontent.com/30196863/34952118-a85854ec-fa3e-11e7-8a9e-fdf8aa96bbf3.png)
Notifications panel
--- 
![image](https://user-images.githubusercontent.com/30196863/34952173-dbef5292-fa3e-11e7-8b22-c4a2ddab98bb.png)
Notification Icons panel
---
![image](https://user-images.githubusercontent.com/30196863/34952213-05bea67c-fa3f-11e7-8d83-69bb9ee8bf10.png)
App Menu panel
---

**Steps to reproduce (if you know)**

Set the default theme to be "Pop-dark-slim" also enable "Global Dark Theme" through "Gnome Tweak Tool". 
While almost everything just gone dark these panels are not. 
Just open the panels and have a look.

**Expected behaviour**

Set the default theme to be "Pop-dark-slim" also enable "Global Dark Theme" through "Gnome Tweak Tool". 
While almost everything just gone dark these panels are not, but if they'll go too, then it'll be awesome.

**Other Notes**

Well, I'm not sure, if it's a default behaviour or a bug.

**Comment by isantop** [comment]
GNOME Shell and GTK use separate themes because they are written in different toolkits. In order to change the theme of the top bar (as well as other Shell-related components), you will need to install the User Themes Gnome extension. This will let you change the theme in Tweak Tool

**Comment by MostHated** [comment]
Sorry to bring up an old issue, but this is awfully strange. I have Pop!_OS 19.04 installed on both my desktop and my laptop. Both are setup identically, and using the dark theme but my Desktop has white backgrounds for the sub menus in the top bar, but my laptop has everything matching just fine.

**Comment by akshymalvia** [comment]
Install 'User Themes' shell extension and then set the desired theme for
Gnome shell too, using Gnome Tweaks.

Regards

**Comment by MostHated** [comment]
That is done on both systems, yet the desktop has white backgrounds on the top bar sub menus as well as if you hit Alt + F2, that popup is also white. My laptop is not like that, everything is dark. Both are using Gnome tweaks and both are setup the same.
