### ISSUE TITLE
Add support for 32 bit EFI on 64 bit ISOs

### ISSUE THREAD

**Issue by thomasstevenson** [pop-os/iso#204]
It is currently not possible to install vanilla versions of Ubuntu-based distros on computers with 32 bit EFIs, such as newer Intel Atom, Pentium, and Celeron (Apollo Lake) processors as well as the first Intel-based Macs. Linuxium has created a script called "isorespin.sh" to add this support (it looks like it adds the grub-efi-ia32 packages to the iso): http://linuxiumcomau.blogspot.com/2018/03/ubuntu-16044-for-intel-atom-and-apollo.html

Fedora has a page on their Wiki about this, which could be of use here: https://fedoraproject.org/wiki/Changes/32BitUefiSupport

Perhaps it could be a good idea to add support for 32 bit EFIs on 64 bit ISOs in the iso build system so Pop OS could work on more computers by default.

**Comment by brs17** [comment]
Thank you for filing this issue @thomasstevenson . We really appreciate the feedback/recommendation. This definitely looks interesting although it does not really align with our current goals for Pop!_OS. I'd say go ahead and share this in our [Pop!_Chat](http://chat.pop-os.org/) where you may find some community members interested.
