### ISSUE TITLE
Bootsplash Doesn't Appear on Boot

### ISSUE THREAD

**Issue by jlacroix82** [pop-os/iso#205]
I am not sure if this is the correct place to report this, but the boot splash screen doesn't appear in 18.04 during boot. During installation, I chose to encrypt my disk. The boot splash did appear in 17.10 on this same laptop, but doesn't appear in 18.04. As a result, the text telling me to unlock the screen is so tiny I can barely read it. In fact, I thought the boot had failed until I saw the text in the top-left corner, and I almost reinstalled thinking the installation had failed.

**Comment by mmstick** [comment]
It's been removed because it causes issue with some graphics cards and the encryption prompt. If you want to enable it, you can do the following:

```
sudo apt install plymouth-theme-pop-logo
```

## EFI

Edit `/etc/kernelstub/configuration` and add `splash` to the `kernel_options` in the `user` section.

```
sudo kernelstub -v
```

## BIOS

```
sudo apt purge grub-pop-disable-splash
```

**Comment by koyuawsmbrtn** [comment]
Would it be possible to only enable it on the Intel/AMD images since Nvidia's drivers are dorky?

**Comment by isantop** [comment]
A large part of why it was removed was due to the animation taking longer than the system takes to boot. In effect, the animation would start, the boot would finish, and then the computer sits playing the animation for a full second or so before the boot can finish. Removing the splash screen thus significantly cuts back on boot times.

**Comment by jlacroix82** [comment]
How significant are we talking?
IMHO, not having a splash screen doesn't present a good experience to the user. In my case, I literally thought my install failed, I could barely read the text asking me for the unlock password. I can certainly understand wanting to make the boot time faster, but if the difference is only 1-2 seconds, I'd say having a splash screen is worth it. The end-user experience will degrade a bit from not having this.

**Comment by WatchMkr** [comment]
Hey Jay, we will be making a simple GUI for the password prompt.

Also, I think you're running from an install just before release. If you run "sudo update-initramfs -u" I believe the console font size will increase.

**Comment by jlacroix82** [comment]
It's the final version, the font size did get larger, but it was still very jarring. The rest of the distribution is extremely beautiful and well-designed, and the lack of a boot splash looks very out of place.

**Comment by brs17** [comment]
https://github.com/pop-os/plymouth-theme/pull/5 Should close this issue.

**Comment by DevSaumyadip** [comment]
> It's been removed because it causes issue with some graphics cards and the encryption prompt. If you want to enable it, you can do the following:
> 
> ```
> sudo apt install plymouth-theme-pop-logo
> ```
> 
> ## EFI
> Edit `/etc/kernelstub/configuration` and add `splash` to the `kernel_options` in the `user` section.
> 
> ```
> sudo kernelstub -v
> ```
> 
> ## BIOS
> ```
> sudo apt purge grub-pop-disable-splash
> ```

Does not work for me on 20.04 LTS, can anyone help

**Comment by felkal** [comment]
> > It's been removed because it causes issue with some graphics cards and the encryption prompt. If you want to enable it, you can do the following:
> > ```
> > sudo apt install plymouth-theme-pop-logo
> > ```
> > 
> > 
> > ## EFI
> > Edit `/etc/kernelstub/configuration` and add `splash` to the `kernel_options` in the `user` section.
> > ```
> > sudo kernelstub -v
> > ```
> > 
> > 
> > ## BIOS
> > ```
> > sudo apt purge grub-pop-disable-splash
> > ```
> 
> Does not work for me on 20.04 LTS, can anyone help

Same for me, any suggestions?

**Comment by gerazo** [comment]
After installing `plymouth-theme-pop-logo` package, you should select this plymouth theme as well. After
`sudo update-alternatives --config default.plymouth`
select the pop-logo theme instead of the current pop-basic one, and update initramfs
`sudo update-initramfs -u`
