### ISSUE TITLE
gpg: no valid OpenPGP data found.

### ISSUE THREAD

**Issue by c-edw** [pop-os/iso#207]
**Reporter info**
```
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.10"
VERSION_ID="17.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
```

**Issue/Bug Description**
On the `distinst` branch, I have executed `deps.sh` and then `make` to begin the build. The process will run, but fails after a while with:
```
gpg: no valid OpenPGP data found.
mk/chroot.mk:23: recipe for target 'build/pop-os/18.04/chroot' failed
make: *** [build/pop-os/18.04/chroot] Error 2
```

**Expected behavior**
The ISO should finish building and be available in the build directory.

**Other Notes**
Contents of `build/pop-os/18.04/` is `chroot.partial` and `debootstrap`. After the initial (failing) build, running `buildchain.sh` gives me the same error message mentioned above. This leads me to believe that the very last part of the process is failing. I also getting the error on the `master` branch.

Thanks!

**Comment by mmstick** [comment]
Make sure you've done this:

```
mmstick:/mnt/data/Sources/iso# gpg --recv-keys 204DD8AEC33A7AFF
gpg: key 204DD8AEC33A7AFF: public key "Pop OS (ISO Signing Key) <info@system76.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

You will also need to have have uploaded your own GPG key to a keyserver (ie: keyserver.ubuntu.com).

```sh
gpg --full-generate-key
gpg --send-keys --keyserver keyserver.ubuntu.com ${YOUR_KEY_ID_HERE}
```

Then I've been running:

```sh
env GPG_NAME=${YOUR_KEY_ID_HERE} make
```

**Comment by c-edw** [comment]
@mmstick Ah, did not see that. They don't seem to be mentioned in the README on master though. Is it worth adding it in there, or is the `distinst` branch going to be merged sometime soon?

**Comment by jackpot51** [comment]
Yes, the distinst branch is used to build 18.04, so it will be merged soon
