### ISSUE TITLE
Error 16 - Cant install Pop! os

### ISSUE THREAD

**Issue by KyokoX** [pop-os/iso#216]
**Distribution** 
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 
**Related Application and/or Package Version**  
N: Unable to locate package NAME

**Issue/Bug Description:** 
Cant install OS from usb driver (using advanced option). Problems with mounted partitions, but they already have been unmounted trough windows. 

**Steps to reproduce:** 
INFO: Logging enabled
INFO: Starting installation
INFO: libdistinst: obtaining disk information from /dev/sda
INFO: libdistinst: obtaining serial model from /dev/sda
INFO: libdistinst: opening disk at /dev/sda
INFO: libdistinst: obtaining partition information from /dev/sda2
INFO: libdistinst: obtaining disk information from /dev/nvme0n1
INFO: libdistinst: obtaining serial model from /dev/nvme0n1
INFO: libdistinst: opening disk at /dev/nvme0n1
INFO: libdistinst: obtaining partition information from /dev/nvme0n1p1
INFO: libdistinst: obtaining partition information from /dev/nvme0n1p2
INFO: libdistinst: obtaining partition information from /dev/nvme0n1p3
INFO: libdistinst: obtaining partition information from /dev/nvme0n1p4
INFO: libdistinst: obtaining partition information from /dev/nvme0n1p5
INFO: libdistinst: obtaining partition information from /dev/nvme0n1p6
INFO: libdistinst: obtaining partition information from /dev/nvme0n1p8
INFO: libdistinst: obtaining partition information from /dev/nvme0n1p9
INFO: libdistinst: obtaining partition information from /dev/nvme0n1p7
INFO: libdistinst: installing Config { hostname: "pop-os", keyboard_layout: "us", keyboard_model: None, keyboard_variant: None, old_root: None, lang: "en_US.UTF-8", remove: "/cdrom/casper/filesystem.manifest-remove", squashfs: "/cdrom/casper/filesystem.squashfs", flags: 3 } with Efi
INFO: libdistinst: starting initializing step
INFO: Initializing
INFO: libdistinst: devices to modify: ["/dev/nvme0n1p8", "/dev/nvme0n1p9"]
INFO: libdistinst: obtaining list of physical volumes
INFO: libdistinst: volume map: {}
INFO: libdistinst: searching for device maps to deactivate
INFO: libdistinst: checking if /dev/mapper/control needs to be marked
INFO: libdistinst: pvs: []
INFO: libdistinst: unmounting device mounted at /cdrom
ERROR: device unmount error: unable to unmount partition(s): Device or resource busy (os error 16)
ERROR: initializing error: unable to unmount partition(s): Device or resource busy (os error 16)

**Other Notes:** 
I dont have cdrom and I am using ssd. Trying to make dualboot

 Sorry for not posting this at the chat, i cant register new account down there so github  is the only hope. Newbie to Linux

**Comment by matticala** [comment]
I have exactly the same issue on Dell 5520. I am trying to dual-boot alongside Ubuntu 16.04

**Comment by thiagoluis** [comment]
I have the same problem ->

> ERROR: device unmount error: unable to unmount partition(s): Device or resource busy (os error 16)
> ERROR: initializing error: unable to unmount partition(s): Device or resource busy (os error 16)

**Comment by loxK** [comment]
Too bad, I wish I found this workaround before ... I had to go on, and went for Ubuntu

**Comment by Janglee123** [comment]
Solution works but they can update there iso.

**Comment by brs17** [comment]
The iso was updated yesterday afternoon. This issue should no longer happen on the new iso(25). I am going to close this issue but feel free to reopen/comment if you continue to have issues.
