### ISSUE TITLE
How can I install pop os with wubi ?

### ISSUE THREAD

**Issue by cata0309** [pop-os/iso#227]
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by mmstick** [comment]
It can't, and shouldn't. [WUBI was discontinued in 2013](https://www.omgubuntu.co.uk/2013/04/wubi-advice).

**Comment by cata0309** [comment]
But now it isn't discontinued anymore. It supports the latest version of
Ubuntu.

mar., 5 feb. 2019, 01:03 Michael Murphy <notifications@github.com> a scris:

**Comment by ahoneybun** [comment]
The project is still discontinued and quite dead. 

https://en.wikipedia.org/wiki/Wubi_(software)
