### ISSUE TITLE
19.04 ISO testing

### ISSUE THREAD

**Issue by jackpot51** [pop-os/iso#235]
- [x] Intel
  - [x] BIOS
  - [x] EFI
  - [x] HiDPI
  - [x] LoDPI
  - [x] With internet connection
  - [x] Without internet connection
  - [x] Full disk encryption
  - [x] No encryption
  - [x] Custom partitioned
- [x] NVIDIA
  - [x] BIOS
  - [x] EFI
  - [x] HiDPI
  - [x] LoDPI
  - [x] With internet connection
  - [x] Without internet connection
  - [x] Full disk encryption
  - [x] No encryption
  - [x] Custom partitioned
  - [x] RTX series GPU
  - [x] GTX series GPU
  - [x] Make sure switchable graphics (Oryx) installs properly and can switch graphics

**Comment by jackpot51** [comment]
@brs17 please edit the issue description with the correct matrix

**Comment by brs17** [comment]
@jackpot51: Updated. Currently putting together a plan for how to knock this out.

**Comment by brs17** [comment]
Test plan:

INTEL:
- Kudu4 - BIOS, full disk encrypted
- LoDPI, internet connected, no full disk encrypted
- galp3-c - HiDPI, no internet, custom partitioned

NVIDIA:
- thelio-b1 - BIOS, unencrypted, RTX 20x0
- Oryp5 - LoDPI, no internet, custom partitioned
- serw11(1080) - hidpi, internet, encrypted

**Comment by isantop** [comment]
Refresh Install appears to refresh the install.

As an added bonus, it does not delete extra data partitions!

**Comment by ahoneybun** [comment]
Please test suspend as well.

**Comment by brs17** [comment]
Release blocked by: https://gitlab.gnome.org/GNOME/gnome-shell/issues/1084
