### ISSUE TITLE
Cannot install 19.04 - EFI partition too small (524MB)

### ISSUE THREAD

**Issue by luispabon** [pop-os/iso#236]
**Distribution (run `cat /etc/os-release`):**
Not yet. I'm changing from an install of Ubuntu to Pop 19.04 

**Issue/Bug Description:**
I'm doing a custom install, as I have a number of partitions I want to keep. EFI is one of them.

Installer (for the nvidia ISO) doesn't allow me to continue (the red erase and install button is not clickable) as it complains the EFI partition isn't big enough. It is however 524MB (over the 500 recommended) with 418MB free. The current ubuntu 19.04 folder in there is just a few MB so I don't see how pop could need more.

Feels like an installer bug to me.

**Other Notes:**

**Comment by mmstick** [comment]
The requirement is 500MiB, rather than 500MB.

- 500MIB is `1024 * 1024 * 500` bytes, or `1024000` 512-byte sectors.
- 500MB is `1000 * 1000 * 500` bytes, or `976562.5` 512-byte sectors.


Chances are that you're a few sectors below the limit.

**Comment by luispabon** [comment]
The partition is in fact 496 MiB according to df. Still, it has ~250MiB available after installing 18.10 and upgrading to 19.04. What's the rationale for disallowing install when there's enough space in EFI to install whatever needs installing?

To give some background, this is a laptop that originally came with Windows installed (still there), which should be a common enough scenario.

**Comment by mmstick** [comment]
A kernel + initrd today is easily 70-100MiB. We need the guarantee that we have enough room for even larger kernels in the future, the possibility that the user will install other kernels alongside the defaults, or even the room for storing other loaders on the same EFI partition. 250 MiB free itself is pretty close to the limit.

**Comment by dryfish** [comment]
Can you have the EFI boot files in the EFI partitiion and kernel/initrd on a separate partitiion?

**Comment by sofusalbertsen** [comment]
what @dryfish said.
I'd like PopOS to be my next daily driver, dual booting with the pre-installed windows.
But the boot section that have been created by Win is too small for this.

From a non-OS technical person, what is the rationale to have them in the EFI partiotion, and not the approach that Ubuntu does (assuming that they do things differently since they do not have the same restrictions)

**Comment by luispabon** [comment]
It's just the installer complaining the EFI partition is too small, even though it actually isn't. This is on my system:
```
/dev/nvme0n1p1               549M   60M  490M  11% /boot/efi
```

At some point I wiped my storage drive and re-did all partitioning by hand. This is out of reach for the majority of users though, re-creating EFI and boot flags and whatnot does require some level of previous knowledge on how to do this sort of thing.

All EFI booting OS use the same partition for - it's an EFI thing.

**Comment by merj1928** [comment]
I tried to install PopOS with Cosmic Desktop. However, I get a message saying that my boot/efi is too small at 2G. Why?
