### ISSUE TITLE
[CRITICAL] The ISO on Pop! OS website is corrupted for Intel/AMD

### ISSUE THREAD

**Issue by raphaelcasimir** [pop-os/iso#237]
**Distribution (run `cat /etc/os-release`):**
 Tried to download and sha256sum on Pop! OS, Ubuntu.
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
The ISO on Pop! OS website is corrupted for Intel/AMD, but not nvidia.
The sha256 sum I get for Intel / AMD is 6a9be774f23f9c319e2287e3958dc4b859adebb73e7f06170c42cb6b053e11dc

It should be:
b3d271c72522cddc1c1fd327cd07716031171cc65c61cfd08fd8e0fca436e6e9

The install of such ISO fails, independently of the USB etching method.

**Steps to reproduce (if you know):**
`sha256sum *.iso` 

**Expected behavior:**

**Other Notes:**

**Comment by jackpot51** [comment]
I have checked again that the Intel ISO's shasum is as follows:

```
$ sha256sum pop-os_19.04_amd64_intel_4.iso 
b3d271c72522cddc1c1fd327cd07716031171cc65c61cfd08fd8e0fca436e6e9  pop-os_19.04_amd64_intel_4.iso
```

Can you confirm that the link you downloaded is this?

https://pop-iso.sfo2.cdn.digitaloceanspaces.com/19.04/amd64/intel/4/pop-os_19.04_amd64_intel_4.iso

**Comment by nashamri** [comment]
I second that I got the following sha:
```
6a9be774f23f9c319e2287e3958dc4b859adebb73e7f06170c42cb6b053e11dc
```
I downloaded it multiple times from this link
```
https://pop-iso.sfo2.cdn.digitaloceanspaces.com/19.04/amd64/intel/4/pop-os_19.04_amd64_intel_4.iso
```

**Comment by btkostner** [comment]
@raphaelcasimir @nashamri What country do you live in?

**Comment by nashamri** [comment]
This is weird, I changed my DNS to `1.1.1.1` and now I get the correct iso checksum:
```
b3d271c72522cddc1c1fd327cd07716031171cc65c61cfd08fd8e0fca436e6e9
```
@raphaelcasimir possible fix is to check your DNS settings.

**Comment by raphaelcasimir** [comment]
France

**Comment by CGrassin** [comment]
Just tried from France, using my ISP's DNS (Orange), I get the correct checksum:
`b3d271c72522cddc1c1fd327cd07716031171cc65c61cfd08fd8e0fca436e6e9`
Weird...

**Comment by raphaelcasimir** [comment]
I also get the right checksum now without changing my dns which already were 1.1.1.1, 8.8.8.8 backup. When I run a diff between the new ISO and the one previously downloaded they differ but I don't know where. Opening the two files with archive manager the file sizes are not different. It is also impossible that the corruption was the same on my two computers and nashamri's. Maybe a caching server somewhere failed for a moment ?
