### ISSUE TITLE
19.10 debug-iso#7: Installation requires network access

### ISSUE THREAD

**Issue by brs17** [pop-os/iso#246]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 19.10
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
distinst

**Issue/Bug Description:**
Attempting to install from debug iso 7 fails on installation returning the error: `ERROR: configuring chroot error: error installing packages: command failed with exit status exit code 100`.

Reattempting to install while connected to the internet succeeded.

**Comment by jackpot51** [comment]
This is an ISO issue

**Comment by jackpot51** [comment]
Should be fixed in next ISO
