### ISSUE TITLE
[RFE] Use Joliet extension when generating the ISO

### ISSUE THREAD

**Issue by fidencio** [pop-os/iso#248]
By using Joliet (adding `-J` to the `genisoimage` command) we'd have additional metadata in the ISO. Some virtual machine management applications (as virt-manager) expect modern ISOs to have Joliet otherwise, depending on the command line passed, the installation would bail.

One example this is when using:
`virt-install --location /path/to/PopOS.iso --os-variant popos19.10`

As the above command line works for Ubuntu ISOs, users **may** assume it will also work for PopOS ISOs.

**Comment by ids1024** [comment]
Resolved by https://github.com/pop-os/iso/pull/262.
