### ISSUE TITLE
Do not enforce unreasonable EFI partition size limit

### ISSUE THREAD

**Issue by linvain** [pop-os/iso#249]
This is a very bad practice. Now I'm sitting there moving my 500+ GB partition just to grow the EFI partition a few megabytes.

Change this to a warning. Developers have enough expertise to decide for themselves.

**Comment by mmstick** [comment]
Feel free to create a second EFI partition if you can't grow an EFI partition for some reason.

**Comment by linvain** [comment]
@mmstick my assumptions:
1) Not many GNU/Linux distros use so much space on EFI partition, so not many users have their EFI partition >=500 MiB
2) Partition resize could cause data loss (especially EFI partition resize)
3) You force EFI partition minimum size requirement

Therefore you expose many of your users to risk of data loss.

I'd prefer not to install additional bootloader and keeping kernels on their corresponding root partitions.
