### ISSUE TITLE
Updating OS fails to connect using https. Needs to connect using https TLS 1.3, HTTP Strict Transport Security (HSTS) .

### ISSUE THREAD

**Issue by shetakeyourmoneyleaveupoor** [pop-os/iso#285]
**Distribution (run `cat /etc/os-release`):**
 
 Pop_OS  21.10
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

Updating POP_ OS fails to connect using Https

**Steps to reproduce (if you know):**

Go to updates changes servers address to be https. Pop_Os would not accept a secure https connection

**Expected behavior:**

Secure connection to POP_OS updates

**Other Notes:**

**Comment by jacobgkau** [comment]
> Go to updates changes servers address to be https. Pop_Os would not accept a secure https connection

Can you please provide a screenshot of what you're trying to change? Most Ubuntu and Pop!_OS repositories are not served over HTTPS, because they're already cryptographically verified using package signing keys and HTTPS would prevent CDN caching.
