### ISSUE TITLE
Theme breaking apps run in Wine

### ISSUE THREAD

**Issue by jrock2004** [pop-os/iso#29]
**Reporter info**

```
 * Distribution - (run ```lsb_release -a```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
lsb_release -a                                                                             
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

**Actual issue**
While running 1Password in Wine with GTK theming enabled, the menus are all white

**Steps to reproduce (if you knew)**
Install newest version of wine(2.11). Open winecfg and under staging you enable GTK theming. Now install 1Password. When it opens up, the file menu is all white. If you hover over the options the text is black like it should be. 

![image](https://user-images.githubusercontent.com/655716/27755783-06625d92-5dc0-11e7-9998-f288812fdd74.png)

**Expected behaviour**
The text in the file menu should be black since the background is white

**Other Note (feature-request, question, etc...)**
In the chrome Linux version, the 1password dropdown from the extension does the same thing. Maybe this is all on 1Password?

**Comment by ryanleesipes** [comment]
@jrock2004 do you see this in any other WINE applications?

**Comment by jrock2004** [comment]
That is the only app I am using in wine. Maybe I can try installing another app to see if I can reproduce in another app

**Comment by jrock2004** [comment]
Here is winecfg and it has the same issue

![image](https://user-images.githubusercontent.com/655716/28651641-02cd41ec-7251-11e7-8dfb-6805f1a25b96.png)

**Comment by isantop** [comment]
@jrock2004 Any chance you could give it a try with the latest Pop GTK release (2.0.4.2 as of the time of writing). Also, could you post a screenshot using Adwaita, for comparison?
