### ISSUE TITLE
Add theme to integrate QT applications

### ISSUE THREAD

**Issue by haevalencia** [pop-os/iso#30]
This is something that already does GNOME with [adwaita-qt](https://github.com/MartinBriza/adwaita-qt) and the idea is that the QT applications used in Pop! _OS look the same as the GTK + applications using [pop-gtk- theme](https://github.com/system76/pop-gtk-theme).

**Comment by isantop** [comment]
Having a qt theme as well as the GTK theme is a hackaround solution that requires a tremendous amount of effort to maintain. Essentially you have to create two completely separate versions of a theme (in addition to the separate GTK2 and GTK3 versions of the theme).

A better solution given the current resources is to use QGtkStyle to use GTK2 to render qt widgets. This allows qt apps to take advantage of the work to unify GTK2 and GTK3, and works fairly well to get a uniform look and feel.

**Comment by rockiger** [comment]
> A better solution given the current resources is to use QGtkStyle to use GTK2 to render qt widgets. This allows qt apps to take advantage of the work to unify GTK2 and GTK3, and works fairly well to get a uniform look and feel.

Could this be done be default. While it is not hard to `export QT_QPA_PLATFORMTHEME=gtk2` it is a nice touch for new users to not worry about the look of QT apps.

**Comment by konsumer** [comment]
Hmm, this doesn't seem to help with virt-manager:
![Screenshot from 2019-11-09 16-25-30](https://user-images.githubusercontent.com/83857/68536800-a66f6d80-030d-11ea-94ea-1b2906164a13.png)
