### ISSUE TITLE
Boot using a Live USB and NVIDIA iso freezes at 800x600 resolution only

### ISSUE THREAD

**Issue by karolosmagnus** [pop-os/iso#305]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
N/A

**Issue/Bug Description:**
The video resolution after boot using a Live USB with Pop_OS Nvidia ISO was frozen at 800x600 all the time, alhtough my screen supports up to 1920x1080.
My intention was to format my Notebook to reinstall the POP 22.04 LTS.
It was hard install the POP using that resolution. It remained 800x600 including after the system install, because in display options, there was not option to change.

**Steps to reproduce (if you know):**
Download Pop_OS Nvidia iso, move it to a Live USB created with Ventoy software.
Boot with UEFI option enable. 

**Expected behavior:**
Screen resolution automatic changing during and after boot to maximum resolution supported by notebook screen.

**Other Notes:**
Using the Pop_OS intel iso, all procedures flow correctly and screen resolution is right chosen.

**Comment by leviport** [comment]
What kind of NVIDIA graphics card do you have, and is this a desktop or a laptop?

**Comment by karolosmagnus** [comment]
> What kind of NVIDIA graphics card do you have, and is this a desktop or a laptop?

GTX 765M (2gb) and my machine is a laptop.

**Comment by leviport** [comment]
Ah that explains it. NVIDIA dropped support for the GT7xx series cards in the 5xx series driver, which is now the default in the NVIDIA Pop ISO. You'll want to go into Pop Shop and install the 470 driver instead.

**Comment by karolosmagnus** [comment]
> Ah that explains it. NVIDIA dropped support for the GT7xx series cards in the 5xx series driver, which is now the default in the NVIDIA Pop ISO. You'll want to go into Pop Shop and install the 470 driver instead.

Oh thank you very much. I installed the old Pop 20.04 lts that I had saved in my HD and then updated to 22.04. Thanks again. I'll close the comment.
