### ISSUE TITLE
Pop!_OS 24.04 ISO Apps and COSMIC Default Settings

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/iso#332]
- Top Panel Applets
    - [x] Add the Workspaces applet to the front of the top panel
    - [x] Remove Numbered Workspaces
- Dock applets (center section)
    - [x] Launcher Button, Workspaces Button, App Library Button, App Tray, Minimized Windows
- Dock App Tray pinned apps
    - [x] Firefox, cosmic-files, cosmic-edit, cosmic-terminal, cosmic-store, cosmic-settings

- Panel and Dock Settings
    - [x] Set Panel Opacity to 100%
    - [x] Set Dock Opacity to 100%

- Touchpad settings
    - [ ] Enable “Disable while typing”
    - [ ] Enable “Tap to Click”

- Application Library
    - Home
        - [x] Firefox, cosmic-files, cosmic-edit, cosmic-terminal, cosmic-store, cosmic-settings
    - Office
        - [x] Add: Document Scanner, Videos, Image Viewer, Thunderbird (new app)
        - Already there: Document Viewer
    - System
        - [x] Add: IBUS Preferences, Input Method, Language Support, System76 Driver
        - Already there: Disk Usage Analyzer, Firmware Manager, GNOME System Monitor, Power Statistics, Repoman, System Monitor
    - Utilities
        - [x] Add: Popsicle
        - Already there: COSMIC Screenshot, Character Map, Disks, File Roller, Fonts, Passwords and Keys, TeXInfo, Vim

-  Apps to remove
    - [x] gnome-weather, gnome-help, gnome-calculator, IBUS Preferences?
- App to add
    - [x] Thunderbird

**Comment by jackpot51** [comment]
https://github.com/pop-os/desktop/commit/f429cc63709abec3e9237262e7a65892b781dcdc

**Comment by jackpot51** [comment]
App library groups were adjusted in https://github.com/pop-os/cosmic-applibrary/commit/3489c536f30899990569ec82cf255a2048315910 but still need testing.
