### ISSUE TITLE
Patch network-manager-gnome nm-applet.desktop file

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/iso#336]
Add COSMIC to NotShowIn nm-applet.desktop. Submit upstream. network-manager-gnome will be used in COSMIC for the Advanced Network Configuration which will be opened directly from COSMIC Settings for advanced network config.

[Desktop Entry]
Name=NetworkManager Applet
Comment=Manage your network connections
Icon=nm-device-wireless
Exec=nm-applet
Terminal=false
Type=Application
NoDisplay=true
NotShowIn=KDE;GNOME;COSMIC
X-GNOME-UsesNotifications=true
X-Ubuntu-Gettext-Domain=nm-applet

**Comment by mmstick** [comment]
Added to https://github.com/pop-os/network-manager-applet/commits/master_noble/

Looking for where to send a patch to

**Comment by mmstick** [comment]
Submitted https://gitlab.gnome.org/GNOME/network-manager-applet/-/merge_requests/146
