### ISSUE TITLE
COSMIC apps do not open on the 24.04 nvidia ISO 9 when installed on a desktop with nvidia

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/iso#338]

**Comment by Harry-W-Haines-III** [comment]
Just a follow up on this to add more information.  Many other applications and settings cannot be accessed.  Network settings yes, global settings menu, no.  POP_Shop and editor no.  For some reason Firefox does open.  Super+T does not open a terminal.  Can't access journalctl to read any errors.

**Comment by WatchMkr** [comment]
This is fixed in our testing ISOs and will be fixed in the public ISO arriving 9/26.
