### ISSUE TITLE
Gparted Does not work on 24.04 COSMIC

### ISSUE THREAD

**Issue by bluescorpion35** [pop-os/iso#339]
When resizing partition on 24.04 installer with gparted, gparted crashes. 
```
(gpartedbin:18592): Gdk-WARNING **: 16:06:20.095: The program 'gpartedbin' received an X Window System error.

This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 71294 error_code 3 request_code 131 (XInputExtension) minor_code 42)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by bluescorpion35** [comment]
Kde partition manager works right now

**Comment by AbsolutelyNotConspicuous** [comment]
> Kde partition manager works right now

I mean it's a little late. I have to take out the NVMe and reset or bin it.

**Comment by authenticastrology** [comment]
I had the same issue upon install when trying to apply changes.

**Comment by justingoldberg** [comment]
If this is a laptop, you can disconnect all cables and the battery, hold down the power button for 30 seconds. It might be pc repair guy folklore, but it has helped me often enough on laptops that have trouble reaching the POST.

**Comment by AbsolutelyNoContext** [comment]
> If this is a laptop, you can disconnect all cables and the battery, hold down the power button for 30 seconds. It might be pc repair guy folklore, but it has helped me often enough on laptops that have trouble reaching the POST.

Hey there, it was a laptop but sadly it was confirmed the bios did get corrupted and could only be reversed by reflashing. I had spoken to the manufacturer and we had already gone through the CMOS reset.

**Comment by jacobgkau** [comment]
GParted is working as expected in newly-built isos. I'm able to delete, create, and resize existing partitions, and GParted does not crash.

If anyone experiences similar problems with the upcoming Alpha 2 iso or later, please provide more detailed information about your partition layout and the action you're attempting.
