### ISSUE TITLE
No way to go back when you click to set up an enterprise account.

### ISSUE THREAD

**Issue by MooShoe** [pop-os/iso#35]
**Reporter info**

```
 * Distribution - Ubuntu 17.04
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```

**Actual issue**
When you are setting up your account, there is an button to set up an enterprise account. (or something like that) Clicking the button takes you to the page, but you can't go back to setting up a regular account without rebooting. 

I'm not sure if that makes sense?

**Steps to reproduce (if you knew)**
Click that button.

**Expected behaviour**
When I click the back button it should take me to the regular accounts page instead of the slide before your chose to set it up.

**Other Note (feature-request, question, etc...)**

**Comment by kylerschin** [comment]
You can simply click on the activated button to return.
If you need a bit of help, you can watch this.
https://youtu.be/INJf0P8caL8

**Comment by ryanleesipes** [comment]
I don't think that is especially obvious, although that is good that you figured it out @kylerschin - we need to have the text at the bottom (where the button is), change when you choose to set up an enterprise account.

Also, what is an enterprise account? :wink:

**Comment by kylerschin** [comment]
Do you want to close this issue? What steps should we take? Any UI Improvements you want? @ryanleesipes @cassidyjames @Xeboc

**Comment by WatchMkr** [comment]
@kylerschin The solution to this is for the "Previous" button to return the user to the "Account Setup" page rather than back to online accounts.

The "Enterprise Account" button can still toggle on/off but at least "Previous" will do what's expected.

**Comment by ryanleesipes** [comment]
Agreed, @kylerschin this is an excellent thing to try and tackle!

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#56
