### ISSUE TITLE
Bug: Bluetooth won't stay off after restart

### ISSUE THREAD

**Issue by TheMonologueGuy** [pop-os/iso#36]
**Reporter info**
System76 Gazelle (Gaze11)
RAM: 7.7 GiB
Processor: Intel® Core™ i5-6300HQ CPU @ 2.30GHz × 4
Graphics: Intel® HD Graphics 530 (Skylake GT2)
```
 * Distribution - Pop_OS 17.04 64-bit
 * Related Application and/or Package Version - Bluetooth
```

**Actual issue**
Bluetooth can be disabled easily, however it doesn't retain the setting when the system is restarted.

**Steps to reproduce (if you knew)**
Disable Bluetooth
Restart or power cycle device

**Expected behaviour**
I was expecting Bluetooth to remain disabled, especially since I installed tlp-drw along with tlp. With these packages, the function works on Linux Mint Cinnamon.

**Other Note (feature-request, question, etc...)**

**Comment by jackpot51** [comment]
Do you have the System76 driver installed?

**Comment by ryanleesipes** [comment]
@TheMonologueGuy after installing the system76-driver-cli - did you still experience the issue?

@jackpot51 is this something that you have seen before?

**Comment by TheMonologueGuy** [comment]
I never the system76 drivers when I searched for them. I assumed they
were baked into the OS.

**Comment by WatchMkr** [comment]
Hi, @TheMonologueGuy.

Instructions to install the System76 Driver are under the heading "Install System76 Driver" here: http://support.system76.com/articles/restore/

**Comment by ryanleesipes** [comment]
@TheMonologueGuy did that fix the issue?

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#55
