### ISSUE TITLE
System locks up when adjusting the display brightness in the Live boot (ThinkPad T420 4178-6VU)

### ISSUE THREAD

**Issue by nick1297** [pop-os/iso#61]
If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 17.04
Release: 17.04
Codename: zesty
 * Related Application and/or Package Version - Gallium
```

**Issue/Bug Description**
On my ThinkPad T420 4178-6VU with the Intel IGP disabled (along with Optimus), the system locks up if you attempt to adjust the volume with the Intel IGP hidden and nVidia Optimus disabled. This does NOT happen when nVidia Optimus is enabled nor does it happen when the Intel IGP is visible but the nVidia GPU is hidden.
Note: The correct Distro reference is Pop!_OS 17.04. The distro is not reporting itself correctly.

**Steps to reproduce (if you know)**
* On a ThinkPad T420 4178-6VU (or any T420 with the NVS 4200M dGPU) disable nVidia Optimus and force the nVidia graphics on all the time by setting up the system accordingly: Graphics Device: Discrete Graphics/OS Detection for NVIDIA Optimus: Disabled
* Boot Pop!_OS off of a USB drive (Specific USB drive used: SanDisk Cruzer Micro 4GB/SDCZ6-4096RB)
* Let the system boot
* Adjust the display brightness (Note: The test machine has the Fn/Ctrl key swap setting enabled. This likely doesn't matter, but I am mentioning it for completeness.)

**Expected behaviour**
The LCD brightness should adjust without a total system lockup.

**Other Notes**
Terminal output:
pop_os@pop_os:~$ apt policy $Gallium
Package files:
 100 /var/lib/dpkg/status
     release a=now
 500 http://ppa.launchpad.net/system76/pop/ubuntu zesty/main amd64 Packages
     release v=17.04,o=LP-PPA-system76-pop,a=zesty,n=zesty,l=Pop!_OS PPA,c=main,b=amd64
     origin ppa.launchpad.net
 500 http://archive.ubuntu.com/ubuntu zesty-updates/universe amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty-updates,n=zesty,l=Ubuntu,c=universe,b=amd64
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu zesty-updates/restricted amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty-updates,n=zesty,l=Ubuntu,c=restricted,b=amd64
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu zesty-updates/main amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty-updates,n=zesty,l=Ubuntu,c=main,b=amd64
     origin archive.ubuntu.com
 500 http://security.ubuntu.com/ubuntu zesty-security/universe amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty-security,n=zesty,l=Ubuntu,c=universe,b=amd64
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu zesty-security/restricted amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty-security,n=zesty,l=Ubuntu,c=restricted,b=amd64
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu zesty-security/main amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty-security,n=zesty,l=Ubuntu,c=main,b=amd64
     origin security.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu zesty/universe amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty,n=zesty,l=Ubuntu,c=universe,b=amd64
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu zesty/restricted amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty,n=zesty,l=Ubuntu,c=restricted,b=amd64
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu zesty/main amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty,n=zesty,l=Ubuntu,c=main,b=amd64
     origin archive.ubuntu.com
 500 cdrom://Pop_OS 17.04 _Zesty Zapus_ - Release amd64 (20170104) zesty/universe amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty,n=zesty,l=Ubuntu,c=universe,b=amd64
     origin Pop_OS 17.04 _Zesty Zapus_ - Release amd64 (20170104)
 500 cdrom://Pop_OS 17.04 _Zesty Zapus_ - Release amd64 (20170104) zesty/restricted amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty,n=zesty,l=Ubuntu,c=restricted,b=amd64
     origin Pop_OS 17.04 _Zesty Zapus_ - Release amd64 (20170104)
 500 cdrom://Pop_OS 17.04 _Zesty Zapus_ - Release amd64 (20170104) zesty/multiverse amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty,n=zesty,l=Ubuntu,c=multiverse,b=amd64
     origin Pop_OS 17.04 _Zesty Zapus_ - Release amd64 (20170104)
 500 cdrom://Pop_OS 17.04 _Zesty Zapus_ - Release amd64 (20170104) zesty/main amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty,n=zesty,l=Ubuntu,c=main,b=amd64
     origin Pop_OS 17.04 _Zesty Zapus_ - Release amd64 (20170104)
Pinned packages:

**Comment by nick1297** [comment]
This issue also happens on a SanDisk SDZ60-016G (Cruzer Glide 16GB). It does not matter which USB drive is used.

**Comment by isantop** [comment]
As a testing procedure, can you try testing from an Ubuntu GNOME live disk and see if you get the same issues there? That will help us locate the problem and file appropriate upstream bugs (if necessary).

**Comment by nick1297** [comment]
This issue still happens on Ubuntu GNOME. I am using the SDCZ6-4096RB drive, which is actually from ~2006.  I will try my 16GB SanDisk Cruzer and see if it still happens on that drive.

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#50
