### ISSUE TITLE
GNOME Online Accounts - Add CardDav and CalDav Providers

### ISSUE THREAD

**Issue by sarahpandabeara** [pop-os/iso#79]
Add CalDev & CardDev providers (code exists)

**Comment by sarahpandabeara** [comment]
Test what's happening now
Add CalDAV feature - https://bugzilla.gnome.org/show_bug.cgi?id=720519#c8 (https://bugzilla.gnome.org/show_bug.cgi?id=762691)
Review adding popular services and updating existing


gnome intial setup - add online account providers (it's the big 4 now...should show all)

facebook isn't working for photos

documents -> clicking should open in edit mode
    fix user interface view/edit button switching
        view goes into the overflow menu and search remains
    keep universal search (when in edit mode)

make documents searchable from the overlay

Add Caldav & carddav providers in gnome online accounts

Add Fastmail provider

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#48
