### ISSUE TITLE
System Menu > Bluetooth and Location disappear from the menu when disabled

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/iso#8]
They should remain in the menu with the option to enable. 

For Bluetooth "Turn On" and for Location "Enable" to match the corresponding disable language.

Currently, you must go to Settings > Privacy or Settings > Bluetooth to re-enable them.

**Comment by ajyotirmay** [comment]
I have experienced this same bug.

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#57
