### ISSUE TITLE
high ram memory consumption with kernel 4.10.x?

### ISSUE THREAD

**Issue by filipeGamaBR** [pop-os/iso#85]
Hello good night, I am using pop or a few days, with kernel 4.10.35 I noticed a high ram memory consumption around 2.3GB and with few open applications and I realize the system is slow, little fluid and this makes it very difficult to perform the tasks. boot starts around 1,3GB ram I use a lot of virtualbox or boxes too. I have not found any bug and I am loving this system !, has what it takes for day to day, has the quality look well built, beautiful wallpapers has beautiful balance of colors and combinations! Many thanks to all the team for taking initiative to create the POP OS, I am looking forward to new upgrades !.
obs: I had to change the kernel and it looks better.
hardware:
Notbook-Dell i14-5458
intel corei3 5 generation
ram: 4GB ddr3 1.600mhz
Intel HD Graphics 5500

**Comment by kylerchin** [comment]
for me it's high CPU and slightly high RAM on my Galago Pro.

**Comment by isantop** [comment]
This issue was moved to pop-os/pop#46
